apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
{{- tpl ((.Files.Glob "config/**.yml").AsConfig) . | nindent 2 }}
{{- tpl ((.Files.Glob "config/**.conf").AsConfig) . | nindent 2 }}
{{- tpl ((.Files.Glob "config/**.properties").AsConfig) . | nindent 2 }}