apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ .Release.Name }}-secret
type: Opaque
{{- range $path, $bytes := .Files.Glob "config/*.secret" }}
data:
  {{- range $k := $.Files.Lines $path }}
  {{ $a := split ": " $k }}{{ printf "%s: %s" $a._0 ($a._1 | b64enc) }}
  {{- end }}
{{- end }}