apiVersion: v1
kind: Service
metadata:
  name: {{ include "mockserver.fullname" . }}
  labels:
    {{- include "mockserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.type }}
  ports:
  {{- range $k, $v := .Values.services.svc }}
    - name: {{ $v.name }}
      port: {{ $v.port }}
      targetPort: {{ $v.targetport }}
      protocol: {{ $v.protocol }}
      nodePort: {{ $v.nodeport }}
  {{- end }}
  selector:
    {{- include "mockserver.selectorLabels" . | nindent 4 }}