# overrided values.yaml
namespace: monitoring-globosat-dev
environmentType: k3s

replicaCount: 1

image:
#  repository: 144282179143.dkr.ecr.eu-central-1.amazonaws.com/memcached
  repository: k3d-local-registry:5000/memcached
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

services:
  type: ClusterIP
  svc:
    - name: memcached
      port: 11211
      targetport: 11211
      protocol: TCP
      nodeport: 

autoscaling:
  enabled: false