apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "curlbeat.fullname" . }}
  labels:
    {{- include "curlbeat.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
          - name: vollog
            persistentVolumeClaim:
              claimName: pvclog
          {{- $releaseName := .Release.Name -}}
          {{- range $path, $bytes := .Files.Glob (printf "config/**.yml") }}
          - name: {{ base $path | trimSuffix ".yml" }}
            configMap:
              defaultMode: 0755
              name: {{ $releaseName }}-configmap
              items:
              - key: {{ base $path }}
                path: {{ base $path }}
          {{- end }}
          containers:
            - name: curlbeat
              image: "{{ .Values.image.curlbeat }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: CHART_NAME
                  value: "{{ .Chart.Name }}"
                - name: CURLBEATLOG
                  value: "{{ .Values.curlbeatlog }}"
                - name: CURLBEATTMP
                  value: "{{ .Values.curlbeattmp }}"
                {{- range $k, $v := .Values.hosts }}
                - name: {{ $k }}
                  value: "{{ $v }}"
                {{- end }}
              command: 
              - bash
              - -c
              - 'echo "sleep {{ .Values.waitbefore }}; Cronjob launched {{ .Chart.Name }} stdout to "$CURLBEATLOG; mkdir -p $(dirname "${CURLBEATLOG}"); [ ! -f $CURLBEATLOG ] && touch $CURLBEATLOG; [ ! -f "$CURLBEATTMP" ] && touch $CURLBEATTMP; {{ .Values.script }} ; cat $CURLBEATTMP >> $CURLBEATLOG; echo >> $CURLBEATLOG; sleep {{ .Values.waitafter }}; '
              resources: {}
              volumeMounts:
              - name: vollog
                mountPath: /pvclog
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
