

            MASTER01:
              ansible_host: 217.69.8.62
              ansible_ssh_user: "root"
              ansible_ssh_private_key_file: "/home/metairie/.ssh/id_rsa"
              ansible_become: true
              ansible_become_user: "root"


            MASTER02:
              ansible_host: 199.247.13.48
              ansible_ssh_user: "root"
              ansible_ssh_private_key_file: "/home/metairie/.ssh/id_rsa"
              ansible_become: true
              ansible_become_user: "root"


            MASTER03:
              ansible_host: 45.32.147.248
              ansible_ssh_user: "root"
              ansible_ssh_private_key_file: "/home/metairie/.ssh/id_rsa"
              ansible_become: true
              ansible_become_user: "root"

